'use client';
import { useEffect,useMemo,useState } from 'react';
import { getMonthlyObservances,traditionClass,traditionLabel,TRADITIONS,type Category,type Observance,type Tradition } from '../../data/observances';
import { displayObservanceName } from '../../lib/locale-display';
import { useLanguage,type ChurchPreference } from './LanguageProvider';

const categories:Category[]=['saint','feast','marian','apostle','martyr','fast'];
function matrix(year:number,month:number){const start=(new Date(Date.UTC(year,month,1)).getUTCDay()+6)%7,days=new Date(Date.UTC(year,month+1,0)).getUTCDate(),cells:(number|null)[]=[...Array.from({length:start},()=>null),...Array.from({length:days},(_,i)=>i+1)];while(cells.length%7)cells.push(null);return cells}
function iso(year:number,month:number,day:number){return`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
type Country={countryCode:string;name:string};

export default function CalendarExplorer(){
 const now=new Date(),{locale,copy,country,church,setChurch}=useLanguage();const[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()),[category,setCategory]=useState<'all'|Category>('all'),[region,setRegion]=useState(country??'GLOBAL'),[countries,setCountries]=useState<Country[]>([]),[loading,setLoading]=useState(false);
 useEffect(()=>{if(country&&region==='GLOBAL')setRegion(country)},[country,region]);
 useEffect(()=>{fetch('/api/v1/religious-holidays?mode=countries').then(response=>response.ok?response.json():null).then(payload=>{if(Array.isArray(payload?.data))setCountries(payload.data)}).catch(()=>undefined)},[]);
 const filters={tradition:church==='all'?undefined:church,category:category==='all'?undefined:category,country:region==='GLOBAL'?undefined:region};
 const fallback=useMemo(()=>getMonthlyObservances(year,month,locale,filters),[year,month,locale,church,category,region]);const[items,setItems]=useState<Observance[]>(fallback);
 useEffect(()=>{setItems(fallback)},[fallback]);
 useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams({year:String(year),month:String(month+1),locale,live:'1'});if(church!=='all')params.set('tradition',church);if(category!=='all')params.set('category',category);if(region!=='GLOBAL')params.set('country',region);setLoading(true);fetch(`/api/v1/observances?${params}`,{signal:controller.signal}).then(response=>response.ok?response.json():Promise.reject(new Error('Calendar request failed'))).then(payload=>{if(Array.isArray(payload?.data))setItems(payload.data)}).catch(error=>{if(error?.name!=='AbortError')setItems(fallback)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[year,month,locale,church,category,region,fallback]);
 const weekdays=useMemo(()=>{const base=new Date(Date.UTC(2026,0,5));return Array.from({length:7},(_,index)=>new Intl.DateTimeFormat(locale,{weekday:'short',timeZone:'UTC'}).format(new Date(base.getTime()+index*86400000)))},[locale]);
 const regionNames=new Intl.DisplayNames([locale],{type:'region'});function shift(value:number){const date=new Date(Date.UTC(year,month+value,1));setYear(date.getUTCFullYear());setMonth(date.getUTCMonth())}
 const feedParams=new URLSearchParams({locale});if(category!=='all')feedParams.set('category',category);if(region!=='GLOBAL')feedParams.set('country',region);
 return <div className="page-stack"><section className="page-hero compact-hero"><div><span className="eyebrow">{copy.global} · {copy.liveData}</span><h1>{copy.calendarTitle}</h1><p>{copy.calendarIntro}</p></div><div className="hero-symbol">☼</div></section>
  <section className="filter-panel"><div className="filter-group"><label>{copy.tradition}</label><select value={church} onChange={event=>setChurch(event.target.value as ChurchPreference)}><option value="all">{copy.all}</option>{TRADITIONS.map(value=><option key={value} value={value}>{traditionLabel(copy,value)}</option>)}</select></div><div className="filter-group"><label>{copy.category}</label><select value={category} onChange={event=>setCategory(event.target.value as 'all'|Category)}><option value="all">{copy.allCategories}</option>{categories.map(value=><option key={value} value={value}>{copy[value]}</option>)}</select></div><div className="filter-group"><label>{copy.country}</label><select value={region} onChange={event=>setRegion(event.target.value)}><option value="GLOBAL">{copy.global}</option>{countries.map(value=><option key={value.countryCode} value={value.countryCode}>{regionNames.of(value.countryCode)??value.name}</option>)}</select></div>{country?<button className="btn btn-tertiary filter-action" onClick={()=>setRegion(country)}>{copy.localSuggestion}</button>:null}</section>
  <section className="calendar-card"><div className="calendar-toolbar"><button className="icon-button" aria-label={copy.previous} onClick={()=>shift(-1)}>←</button><h2>{new Intl.DateTimeFormat(locale,{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(year,month,1)))}</h2><button className="icon-button" aria-label={copy.next} onClick={()=>shift(1)}>→</button></div>{loading?<div className="data-loading" aria-live="polite">{copy.loading}</div>:null}<div className="calendar-scroll"><div className="calendar-grid">{weekdays.map(day=><div className="weekday" key={day}>{day}</div>)}{matrix(year,month).map((day,index)=>{const date=day?iso(year,month,day):'',list=day?items.filter(item=>item.dateISO===date):[],today=Boolean(day&&date===iso(now.getFullYear(),now.getMonth(),now.getDate()));return <div className={`calendar-cell${day?'':' blank'}${today?' is-today':''}`} key={`${date}-${index}`}>{day?<><a className="day-number" href={`/day/${date}`}>{day}</a><div className="calendar-items">{list.slice(0,10).map(item=>{const name=displayObservanceName(item.names,locale,item.name);return name?<a className={`calendar-observance ${traditionClass(item.traditions[0])}`} href={`/day/${date}`} key={item.id}>{name}</a>:null})}</div>{list.length>10?<a className="calendar-more" href={`/day/${date}`}>+{list.length-10}</a>:null}</>:null}</div>})}</div></div>{!loading&&!items.length?<div className="empty-state inline"><span>✦</span><p>{copy.noResults}</p></div>:null}</section>
  <section className="subscription-strip"><div><span className="eyebrow">ICS · Google · Apple · Outlook</span><h2>{copy.addCalendar}</h2></div><div className="button-row"><a className="btn btn-primary" href={`/api/ical/${church==='all'?'all':church}?${feedParams}`}>{copy.feedAll}</a><a className="btn btn-secondary" href={`/api/ical/roman-catholic?locale=${locale}${region!=='GLOBAL'?`&country=${region}`:''}`}>{copy.feedCatholic}</a><a className="btn btn-secondary" href={`/api/ical/eastern-orthodox?locale=${locale}`}>{copy.feedOrthodox}</a></div></section>
 </div>
}
