'use client';
import { LIVE_STREAM_SOURCES } from '../../data/live-streams';
import { SOURCE_CATALOG,traditionLabel } from '../../data/observances';
import { SAINT_BIOGRAPHIES } from '../../data/saint-biographies';
import { getFeatureCopy } from '../../lib/feature-copy';
import { useLanguage } from './LanguageProvider';

const EXTRA_SOURCES=[
 {id:'coptic-io',name:'Coptic.io — Coptic Orthodox API',url:'https://api.coptic.io/docs',kind:'reference',note:'Structured Synaxarium and Coptic calendar API used for discovery. Entries are labelled as cross-checked and should be compared with Church sources.',authority:'Independent Coptic technology project'},
 {id:'nager-date',name:'Nager.Date — Public Holiday API',url:'https://date.nager.at/',kind:'reference',note:'Country public-holiday data. It determines legal public holidays, not the theological or liturgical status of a celebration.',authority:'Open-source public-holiday project'},
 {id:'wikidata-labels',name:'Wikidata multilingual labels',url:'https://www.wikidata.org/',kind:'reference',note:'Multilingual entity labels used to improve saint-name presentation. Liturgical dates and Church status continue to come from Church calendar sources.',authority:'Wikimedia Foundation community data'}
] as const;
export default function CopyrightSources(){
 const{locale,copy}=useLanguage(),feature=getFeatureCopy(locale),biographySources=[...new Map(SAINT_BIOGRAPHIES.flatMap(item=>item.sources).map(source=>[source.url,source])).values()];
 const sections=[[feature.copyrightContent,'The Santos do Dia interface, original editorial summaries, software structure and branding are project content unless another attribution is shown. Source code and third-party packages retain their respective licences.'],[feature.copyrightData,'Church calendars, saint names, patronages, historical summaries and country holidays use separate source tiers. A liturgical celebration is never automatically classified as a legal public holiday.'],[feature.copyrightImages,'Only public-domain, openly licensed or expressly authorised visual material should be published. Every image must retain author, source and licence metadata.'],[feature.copyrightEmbeds,'Live video and recordings remain hosted by the originating institution or platform. Santos do Dia links to the official external page and does not claim ownership of the broadcast.'],[feature.copyrightCorrections,'Rights holders and institutions may request a correction, updated attribution or removal. Changes must be recorded in GitHub so that production remains reproducible.']];
 return <div className="page-stack copyright-page"><section className="page-hero compact-hero"><div><span className="eyebrow">Copyright · provenance · licensing</span><h1>{feature.copyrightTitle}</h1><p>{feature.copyrightIntro}</p></div><div className="hero-symbol">©</div></section><section className="rights-grid">{sections.map(([title,body],index)=><article className="rights-card" key={title}><span>0{index+1}</span><h2>{title}</h2><p>{body}</p></article>)}</section>
  <section className="notice-card"><strong>Source hierarchy</strong><p>1. Official Church calendar or national proper. 2. Official Church directory or institutional publication. 3. Structured reference used for discovery and marked for cross-checking. 4. Multilingual entity data used only for names and search.</p></section>
  <section className="source-list-section"><div className="section-heading"><div><span className="eyebrow">Calendar · patronage · validation</span><h2>{feature.copyrightData}</h2></div></div><div className="source-list">{SOURCE_CATALOG.map(source=><article className="source-card" key={source.id}><div><span className="source-kind">{source.kind==='official'?copy.sourceOfficial:copy.sourceReference}</span><h3>{source.name}</h3><p>{source.note}</p><div className="tag-row">{source.traditions.map(value=><span key={value}>{traditionLabel(copy,value)}</span>)}{source.licenseNote?<span>{source.licenseNote}</span>:null}</div></div><a className="text-link" href={source.url} target="_blank" rel="noreferrer">{copy.navSources} ↗</a></article>)}{EXTRA_SOURCES.map(source=><article className="source-card" key={source.id}><div><span className="source-kind">{copy.sourceReference}</span><h3>{source.name}</h3><p>{source.note}</p><div className="tag-row"><span>{source.authority}</span></div></div><a className="text-link" href={source.url} target="_blank" rel="noreferrer">{copy.navSources} ↗</a></article>)}</div></section>
  {biographySources.length?<section className="source-list-section"><div className="section-heading"><div><span className="eyebrow">Biography · editorial history · OSINT</span><h2>Biography sources</h2></div></div><div className="source-list">{biographySources.map(source=><article className="source-card" key={source.url}><div><span className="source-kind">{feature.officialSource}</span><h3>{source.name}</h3><div className="tag-row"><span>{source.publisher}</span><span>{source.language.toUpperCase()}</span></div></div><a className="text-link" href={source.url} target="_blank" rel="noreferrer">{feature.officialSource} ↗</a></article>)}</div></section>:null}
  <section className="source-list-section"><div className="section-heading"><div><span className="eyebrow">Live · archive · official media</span><h2>{feature.copyrightEmbeds}</h2></div></div><div className="source-list">{LIVE_STREAM_SOURCES.map(source=><article className="source-card" key={source.id}><div><span className="source-kind">{feature.officialSource}</span><h3>{source.organization}</h3><div className="tag-row"><span>{traditionLabel(copy,source.tradition)}</span><span>{feature.verifiedOn}: {source.verifiedAt}</span></div></div><a className="text-link" href={source.sourceUrl} target="_blank" rel="noreferrer">{feature.officialSource} ↗</a></article>)}</div></section><section className="notice-card"><strong>{feature.copyrightNoAffiliation}</strong><p>{copy.disclaimer}</p></section>
 </div>
}
