'use client';
import Link from 'next/link';
import type { Locale } from '../../lib/i18n';
import { useLanguage } from './LanguageProvider';

const copy:Record<Locale,{eyebrow:string;title:string;intro:string;items:Array<{href:string;label:string;body:string}>}>={
 en:{eyebrow:'Start with what you need',title:'One Christian knowledge service, several entry points.',intro:'Begin with today, a saint, a date, a place, a Church, a calendar or the readings. The same knowledge base connects every path.',items:[{href:'/explore',label:'Find a saint',body:'Search by name, profession, need, place or date.'},{href:'/calendar',label:'Explore calendars',body:'Compare celebrations and movable feasts across traditions.'},{href:'/liturgy',label:'Readings and liturgy',body:'Open the liturgical context and daily reading references.'},{href:'/holidays',label:'Explore by place',body:'See religious dates and celebrations by country.'},{href:'/churches',label:'Churches and jurisdictions',body:'Understand traditions, calendars and ecclesiastical territories.'}]},
 pt:{eyebrow:'Comece pelo que procura',title:'Um único serviço de conhecimento cristão, várias portas de entrada.',intro:'Comece por hoje, por um santo, uma data, um lugar, uma Igreja, um calendário ou pelas leituras. A mesma base de conhecimento liga todos os percursos.',items:[{href:'/explore',label:'Encontrar um santo',body:'Pesquise por nome, profissão, necessidade, local ou data.'},{href:'/calendar',label:'Explorar calendários',body:'Compare celebrações e festas móveis entre tradições.'},{href:'/liturgy',label:'Leituras e liturgia',body:'Consulte o enquadramento litúrgico e as referências bíblicas do dia.'},{href:'/holidays',label:'Explorar por lugar',body:'Veja datas religiosas e celebrações por país.'},{href:'/churches',label:'Igrejas e jurisdições',body:'Conheça tradições, calendários e territórios eclesiásticos.'}]},
 es:{eyebrow:'Empiece por lo que busca',title:'Un único servicio de conocimiento cristiano, varias puertas de entrada.',intro:'Empiece por hoy, un santo, una fecha, un lugar, una Iglesia, un calendario o las lecturas. La misma base de conocimiento conecta todos los recorridos.',items:[{href:'/explore',label:'Encontrar un santo',body:'Busque por nombre, profesión, necesidad, lugar o fecha.'},{href:'/calendar',label:'Explorar calendarios',body:'Compare celebraciones y fiestas móviles entre tradiciones.'},{href:'/liturgy',label:'Lecturas y liturgia',body:'Consulte el contexto litúrgico y las referencias bíblicas del día.'},{href:'/holidays',label:'Explorar por lugar',body:'Vea fechas religiosas y celebraciones por país.'},{href:'/churches',label:'Iglesias y jurisdicciones',body:'Conozca tradiciones, calendarios y territorios eclesiásticos.'}]},
 fr:{eyebrow:'Commencez par votre besoin',title:'Un seul service de connaissance chrétienne, plusieurs portes d’entrée.',intro:'Commencez par aujourd’hui, un saint, une date, un lieu, une Église, un calendrier ou les lectures. La même base de connaissances relie tous les parcours.',items:[{href:'/explore',label:'Trouver un saint',body:'Recherchez par nom, profession, besoin, lieu ou date.'},{href:'/calendar',label:'Explorer les calendriers',body:'Comparez les célébrations et fêtes mobiles entre traditions.'},{href:'/liturgy',label:'Lectures et liturgie',body:'Consultez le contexte liturgique et les références bibliques du jour.'},{href:'/holidays',label:'Explorer par lieu',body:'Consultez les dates religieuses et célébrations par pays.'},{href:'/churches',label:'Églises et juridictions',body:'Découvrez les traditions, calendriers et territoires ecclésiastiques.'}]},
 fil:null as never,ru:null as never,sw:null as never,de:null as never,it:null as never,pl:null as never
};

export default function EntryPoints(){
 const{locale}=useLanguage();const text=copy[locale]??copy.en;
 return <section className="entry-points"><div className="section-heading"><div><span className="eyebrow">{text.eyebrow}</span><h2>{text.title}</h2><p>{text.intro}</p></div></div><div className="entry-point-grid">{text.items.map(item=><Link className="entry-point-card" href={item.href} key={item.href}><h3>{item.label}</h3><p>{item.body}</p><span aria-hidden="true">→</span></Link>)}</div><style jsx>{`
 .entry-points{padding:18px 0}.section-heading{max-width:800px}.section-heading p{margin:12px 0 0;color:#637080}.entry-point-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px}.entry-point-card{position:relative;min-height:180px;padding:26px;border-radius:20px;background:#fff;border:1px solid rgba(16,42,67,.09);transition:transform .18s,box-shadow .18s}.entry-point-card:hover,.entry-point-card:focus-visible{transform:translateY(-3px);box-shadow:0 14px 34px rgba(8,27,44,.09)}.entry-point-card h3{margin:0 0 10px;font-family:Georgia,'Times New Roman',serif;font-size:1.35rem;font-weight:600}.entry-point-card p{margin:0;color:#637080;font-size:.9rem}.entry-point-card span{position:absolute;right:24px;bottom:20px;color:#24547a;font-weight:850}@media(max-width:560px){.entry-point-grid{grid-template-columns:1fr}.entry-point-card{min-height:150px}}
 `}</style></section>
}
