'use client';
import { useEffect,useMemo,useState } from 'react';
import { traditionLabel,TRADITIONS,type Tradition } from '../../data/observances';
import type { Locale } from '../../lib/i18n';
import type { ReligiousHoliday } from '../../lib/religious-holidays';
import { useLanguage,type ChurchPreference } from './LanguageProvider';

type Country={countryCode:string;name:string};type Payload={country:string;year:number;tradition:ChurchPreference;publicHolidays:ReligiousHoliday[];churchDates:ReligiousHoliday[]};
const TEXT:Record<Locale,{title:string;intro:string;country:string;year:string;church:string;publicTitle:string;publicIntro:string;churchTitle:string;churchIntro:string;fixed:string;movable:string;public:string;liturgical:string;emptyPublic:string;emptyChurch:string;notice:string;loading:string;source:string}>={
 en:{title:'Religious holidays by country',intro:'Compare legal public holidays with fixed and movable dates in the selected Christian tradition for this year and future years.',country:'Country',year:'Year',church:'Church or tradition',publicTitle:'Religious public holidays',publicIntro:'Christian dates classified as legal public holidays by the selected country.',churchTitle:'Church calendar dates',churchIntro:'Principal fixed and movable dates calculated for the selected Christian tradition.',fixed:'Fixed',movable:'Movable',public:'Public holiday',liturgical:'Liturgical date',emptyPublic:'No Christian public holiday was identified for this country and year.',emptyChurch:'No calculated dates are available for this selection.',notice:'A Church celebration is not automatically a legal public holiday. Regional rules and official calendars may differ.',loading:'Loading holidays…',source:'Sources and method'},
 pt:{title:'Feriados religiosos por país',intro:'Compare os feriados públicos legais com as datas fixas e móveis da tradição cristã selecionada, no ano atual e nos próximos anos.',country:'País',year:'Ano',church:'Igreja ou tradição',publicTitle:'Feriados públicos religiosos',publicIntro:'Datas cristãs classificadas como feriado legal pelo país selecionado.',churchTitle:'Datas do calendário da Igreja',churchIntro:'Principais datas fixas e móveis calculadas para a tradição cristã selecionada.',fixed:'Fixo',movable:'Móvel',public:'Feriado público',liturgical:'Data litúrgica',emptyPublic:'Não foi identificado um feriado público cristão para este país e ano.',emptyChurch:'Não existem datas calculadas para esta seleção.',notice:'Uma celebração da Igreja não é automaticamente um feriado legal. Podem existir regras regionais e diferenças nos calendários oficiais.',loading:'A carregar feriados…',source:'Fontes e método'},
 es:{title:'Festivos religiosos por país',intro:'Compare los festivos públicos legales con las fechas fijas y móviles de la tradición cristiana seleccionada, en el año actual y en los próximos años.',country:'País',year:'Año',church:'Iglesia o tradición',publicTitle:'Festivos públicos religiosos',publicIntro:'Fechas cristianas clasificadas como festivo legal por el país seleccionado.',churchTitle:'Fechas del calendario de la Iglesia',churchIntro:'Principales fechas fijas y móviles calculadas para la tradición cristiana seleccionada.',fixed:'Fijo',movable:'Móvil',public:'Festivo público',liturgical:'Fecha litúrgica',emptyPublic:'No se identificó un festivo público cristiano para este país y año.',emptyChurch:'No hay fechas calculadas para esta selección.',notice:'Una celebración eclesial no es automáticamente un festivo legal. Pueden existir reglas regionales y diferencias entre calendarios oficiales.',loading:'Cargando festivos…',source:'Fuentes y método'},
 fr:{title:'Jours fériés religieux par pays',intro:'Comparez les jours fériés légaux aux dates fixes et mobiles de la tradition chrétienne choisie, pour cette année et les années à venir.',country:'Pays',year:'Année',church:'Église ou tradition',publicTitle:'Jours fériés religieux',publicIntro:'Dates chrétiennes reconnues comme jours fériés légaux par le pays choisi.',churchTitle:'Dates du calendrier de l’Église',churchIntro:'Principales dates fixes et mobiles calculées pour la tradition chrétienne choisie.',fixed:'Fixe',movable:'Mobile',public:'Jour férié',liturgical:'Date liturgique',emptyPublic:'Aucun jour férié chrétien n’a été identifié pour ce pays et cette année.',emptyChurch:'Aucune date calculée pour cette sélection.',notice:'Une célébration ecclésiale n’est pas automatiquement un jour férié légal. Des règles régionales et des différences de calendrier peuvent exister.',loading:'Chargement des jours fériés…',source:'Sources et méthode'},
 fil:{title:'Mga relihiyosong holiday ayon sa bansa',intro:'Ihambing ang legal na holiday at ang nakapirmi o nagbabagong petsa ng napiling tradisyong Kristiyano.',country:'Bansa',year:'Taon',church:'Simbahan o tradisyon',publicTitle:'Mga relihiyosong pampublikong holiday',publicIntro:'Mga petsang Kristiyano na legal na holiday sa napiling bansa.',churchTitle:'Mga petsa sa kalendaryo ng Simbahan',churchIntro:'Pangunahing nakapirmi at nagbabagong petsa ng napiling tradisyon.',fixed:'Nakapirmi',movable:'Nagbabago',public:'Pampublikong holiday',liturgical:'Petsa liturhiko',emptyPublic:'Walang natukoy na Kristiyanong pampublikong holiday.',emptyChurch:'Walang kalkuladong petsa para sa pagpili.',notice:'Ang pagdiriwang ng Simbahan ay hindi awtomatikong legal na holiday.',loading:'Naglo-load…',source:'Mga sanggunian at paraan'},
 ru:{title:'Религиозные праздники по странам',intro:'Сравните государственные выходные с постоянными и переходящими датами выбранной христианской традиции.',country:'Страна',year:'Год',church:'Церковь или традиция',publicTitle:'Религиозные государственные праздники',publicIntro:'Христианские даты, признанные выходными в выбранной стране.',churchTitle:'Даты церковного календаря',churchIntro:'Основные постоянные и переходящие даты выбранной традиции.',fixed:'Постоянная',movable:'Переходящая',public:'Государственный праздник',liturgical:'Литургическая дата',emptyPublic:'Христианские государственные праздники не найдены.',emptyChurch:'Расчётные даты отсутствуют.',notice:'Церковное празднование не обязательно является государственным выходным.',loading:'Загрузка…',source:'Источники и методика'},
 sw:{title:'Sikukuu za kidini kwa nchi',intro:'Linganisha sikukuu za umma na tarehe za kudumu au zinazobadilika za mapokeo ya Kikristo yaliyochaguliwa.',country:'Nchi',year:'Mwaka',church:'Kanisa au mapokeo',publicTitle:'Sikukuu za umma za kidini',publicIntro:'Tarehe za Kikristo zinazotambuliwa kisheria kuwa sikukuu.',churchTitle:'Tarehe za kalenda ya Kanisa',churchIntro:'Tarehe kuu za kudumu na zinazobadilika.',fixed:'Ya kudumu',movable:'Inayobadilika',public:'Sikukuu ya umma',liturgical:'Tarehe ya kiliturujia',emptyPublic:'Hakuna sikukuu ya umma ya Kikristo iliyopatikana.',emptyChurch:'Hakuna tarehe zilizohesabiwa.',notice:'Sikukuu ya Kanisa si lazima iwe sikukuu ya umma kisheria.',loading:'Inapakia…',source:'Vyanzo na mbinu'},
 de:{title:'Religiöse Feiertage nach Land',intro:'Vergleichen Sie gesetzliche Feiertage mit festen und beweglichen Terminen der gewählten christlichen Tradition.',country:'Land',year:'Jahr',church:'Kirche oder Tradition',publicTitle:'Religiöse gesetzliche Feiertage',publicIntro:'Christliche Termine, die im gewählten Land gesetzliche Feiertage sind.',churchTitle:'Kirchliche Kalenderdaten',churchIntro:'Wichtige feste und bewegliche Termine der gewählten Tradition.',fixed:'Fest',movable:'Beweglich',public:'Gesetzlicher Feiertag',liturgical:'Liturgischer Tag',emptyPublic:'Kein christlicher gesetzlicher Feiertag gefunden.',emptyChurch:'Keine berechneten Termine verfügbar.',notice:'Ein kirchlicher Festtag ist nicht automatisch ein gesetzlicher Feiertag.',loading:'Feiertage werden geladen…',source:'Quellen und Methode'},
 it:{title:'Festività religiose per paese',intro:'Confronta le festività pubbliche legali con le date fisse e mobili della tradizione cristiana selezionata.',country:'Paese',year:'Anno',church:'Chiesa o tradizione',publicTitle:'Festività pubbliche religiose',publicIntro:'Date cristiane riconosciute come festività legali nel paese selezionato.',churchTitle:'Date del calendario della Chiesa',churchIntro:'Principali date fisse e mobili della tradizione scelta.',fixed:'Fissa',movable:'Mobile',public:'Festività pubblica',liturgical:'Data liturgica',emptyPublic:'Nessuna festività pubblica cristiana identificata.',emptyChurch:'Nessuna data calcolata disponibile.',notice:'Una celebrazione ecclesiale non è automaticamente una festività legale.',loading:'Caricamento…',source:'Fonti e metodo'},
 pl:{title:'Święta religijne według kraju',intro:'Porównaj ustawowe dni wolne ze stałymi i ruchomymi datami wybranej tradycji chrześcijańskiej.',country:'Kraj',year:'Rok',church:'Kościół lub tradycja',publicTitle:'Religijne dni ustawowo wolne',publicIntro:'Daty chrześcijańskie uznane w wybranym kraju za dni wolne.',churchTitle:'Daty kalendarza kościelnego',churchIntro:'Główne stałe i ruchome daty wybranej tradycji.',fixed:'Stałe',movable:'Ruchome',public:'Dzień ustawowo wolny',liturgical:'Data liturgiczna',emptyPublic:'Nie znaleziono chrześcijańskiego dnia ustawowo wolnego.',emptyChurch:'Brak obliczonych dat.',notice:'Święto kościelne nie zawsze jest ustawowym dniem wolnym.',loading:'Ładowanie…',source:'Źródła i metoda'}
};

export default function ReligiousHolidayExplorer(){
 const{locale,copy,country:detectedCountry,church,setChurch}=useLanguage(),text=TEXT[locale],current=new Date().getFullYear(),[country,setCountry]=useState(detectedCountry??'PT'),[year,setYear]=useState(current),[countries,setCountries]=useState<Country[]>([]),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(false);
 useEffect(()=>{if(detectedCountry)setCountry(detectedCountry)},[detectedCountry]);
 useEffect(()=>{fetch('/api/v1/religious-holidays?mode=countries').then(response=>response.ok?response.json():null).then(payload=>{if(Array.isArray(payload?.data))setCountries(payload.data)}).catch(()=>undefined)},[]);
 useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams({country,year:String(year),locale,tradition:church});setLoading(true);fetch(`/api/v1/religious-holidays?${params}`,{signal:controller.signal}).then(response=>response.ok?response.json():Promise.reject(new Error('Holiday request failed'))).then(payload=>setData(payload?.data??null)).catch(error=>{if(error?.name!=='AbortError')setData(null)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[country,year,locale,church]);
 const regionNames=useMemo(()=>new Intl.DisplayNames([locale],{type:'region'}),[locale]),years=Array.from({length:16},(_,index)=>current-1+index);
 function list(items:ReligiousHoliday[]|undefined,publicList:boolean){return items?.length?<div className="holiday-list">{items.map(item=><article className="holiday-row" key={item.id}><time dateTime={item.date}><strong>{new Intl.DateTimeFormat(locale,{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${item.date}T00:00:00Z`))}</strong><span>{new Intl.DateTimeFormat(locale,{weekday:'long',timeZone:'UTC'}).format(new Date(`${item.date}T00:00:00Z`))}</span></time><div><h3>{item.name}</h3><div className="holiday-tags"><span>{item.kind==='fixed'?text.fixed:text.movable}</span><span>{publicList?text.public:text.liturgical}</span>{item.tradition?<span>{traditionLabel(copy,item.tradition)}</span>:null}</div>{item.localName&&item.localName!==item.name?<small>{item.localName}</small>:null}</div></article>)}</div>:<div className="empty-state inline"><span>✦</span><p>{publicList?text.emptyPublic:text.emptyChurch}</p></div>}
 return <div className="page-stack holidays-page"><section className="page-hero compact-hero"><div><span className="eyebrow">Country · law · liturgical calculation</span><h1>{text.title}</h1><p>{text.intro}</p></div><div className="hero-symbol">◎</div></section><section className="holiday-controls"><label><span>{text.country}</span><select value={country} onChange={event=>setCountry(event.target.value)}>{countries.map(item=><option key={item.countryCode} value={item.countryCode}>{regionNames.of(item.countryCode)??item.name}</option>)}</select></label><label><span>{text.year}</span><select value={year} onChange={event=>setYear(Number(event.target.value))}>{years.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label><span>{text.church}</span><select value={church} onChange={event=>setChurch(event.target.value as ChurchPreference)}><option value="all">{copy.all}</option>{TRADITIONS.map(value=><option key={value} value={value}>{traditionLabel(copy,value)}</option>)}</select></label></section>{loading?<div className="data-loading" aria-live="polite">{text.loading}</div>:null}<section className="holiday-columns"><article className="holiday-section"><span className="eyebrow">Law · country</span><h2>{text.publicTitle}</h2><p>{text.publicIntro}</p>{list(data?.publicHolidays,true)}</article><article className="holiday-section"><span className="eyebrow">Church · calculation</span><h2>{text.churchTitle}</h2><p>{text.churchIntro}</p>{list(data?.churchDates,false)}</article></section><section className="notice-card"><strong>{text.notice}</strong><p>{text.source}: Nager.Date, calendários institucionais e regras de cálculo documentadas na página de fontes.</p></section></div>
}
