'use client';
import { useEffect,useMemo,useState } from 'react';
import { getObservancesForDate,traditionClass,traditionLabel,type Observance } from '../../data/observances';
import { displayObservanceName } from '../../lib/locale-display';
import { useLanguage } from './LanguageProvider';

function localDateISO(){const date=new Date();return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
export default function TodayPanel(){
 const{locale,copy,country,countryName,church}=useLanguage(),dateISO=localDateISO();
 const fallback=useMemo(()=>getObservancesForDate(dateISO,locale,{tradition:church==='all'?undefined:church,country}),[dateISO,locale,church,country]);const[items,setItems]=useState<Observance[]>(fallback),[loading,setLoading]=useState(false);
 useEffect(()=>{setItems(fallback)},[fallback]);
 useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams({date:dateISO,locale,live:'1'});if(church!=='all')params.set('tradition',church);if(country)params.set('country',country);setLoading(true);fetch(`/api/v1/observances?${params}`,{signal:controller.signal}).then(response=>response.ok?response.json():Promise.reject(new Error('Today request failed'))).then(payload=>{if(Array.isArray(payload?.data))setItems(payload.data)}).catch(error=>{if(error?.name!=='AbortError')setItems(fallback)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[dateISO,locale,church,country,fallback]);
 const label=new Intl.DateTimeFormat(locale,{dateStyle:'full'}).format(new Date(`${dateISO}T12:00:00`));
 return <section className="today-panel"><div className="today-date-card"><span className="eyebrow">{copy.today}</span><strong className="today-day">{new Date(`${dateISO}T12:00:00`).getDate()}</strong><span className="today-date-label">{label}</span>{countryName?<span className="region-pill">{copy.suggestedRegion}: {countryName}</span>:null}</div><div className="today-content"><div className="section-heading compact"><div><span className="eyebrow">{loading?copy.loading:copy.liveData}</span><h2>{copy.saintsToday}</h2></div><a className="text-link" href={`/day/${dateISO}`}>{copy.openDay} →</a></div>{items.length?<div className="observance-list">{items.slice(0,18).map(item=>{const name=displayObservanceName(item.names,locale,item.name);return name?<article className="observance-row" key={item.id}><div className={`tradition-dot ${traditionClass(item.traditions[0])}`}/><div><h3>{name}</h3><p>{item.traditions.map(value=>traditionLabel(copy,value)).join(' · ')} · {copy[item.category]}</p></div></article>:null})}</div>:<div className="empty-state"><span>✦</span><p>{loading?copy.loading:copy.noObservances}</p></div>}<div className="today-actions"><a className="btn btn-primary" href="/calendar">{copy.viewCalendar}</a><a className="btn btn-secondary" href={`/api/ical/${church==='all'?'all':church}?locale=${locale}${country?`&country=${country}`:''}`}>{copy.downloadIcs}</a></div></div></section>
}
