import type { Locale, LocalizedText } from './i18n';
import { buildLocalizedNames } from './observance-localization';
import type { Category, Observance, ObservanceFilters, Tradition, ValidationStatus } from '../data/observances';

export type ExpandedSourceHealth={sourceId:string;ok:boolean;checkedAt:string;count:number;message?:string};
type RecordValue=Record<string,unknown>;
const TIMEOUT=14_000;

function record(value:unknown):RecordValue|undefined{return value&&typeof value==='object'&&!Array.isArray(value)?value as RecordValue:undefined}
function text(value:unknown):string|undefined{return typeof value==='string'&&value.trim()?value.replace(/\s+/g,' ').trim():typeof value==='number'?String(value):undefined}
function slug(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90)||'observance'}
function category(name:string):Category{const lower=name.toLowerCase();if(/fast|lent|abstin|jejum|ayuno|пост/.test(lower))return'fast';if(/mary|marian|virgin|theotokos|our lady|madonna|maria|богород/.test(lower))return'marian';if(/apostle|evangelist|apóstol|apóstolo|апостол/.test(lower))return'apostle';if(/martyr|mártir|martire|мучен/.test(lower))return'martyr';if(/lord|christ|nativity|epiphany|theophany|ascension|pentecost|cross|resurrection|easter|pascha|feast|solemnity/.test(lower))return'feast';return'saint'}
function make(args:{sourceId:string;externalId?:string;dateISO:string;name:string;sourceLocale:Locale;tradition:Tradition;calendarSystem:Observance['calendarSystem'];validationStatus:ValidationStatus;summary?:string}):Observance{const[,month,day]=args.dateISO.split('-').map(Number);const names=buildLocalizedNames(args.name,{[args.sourceLocale]:args.name} as Partial<Record<Locale,string>>) as LocalizedText;return{id:`${args.sourceId}-${slug(args.externalId??args.name)}-${args.dateISO}`,externalId:args.externalId,month,day,dateISO:args.dateISO,traditions:[args.tradition],category:category(args.name),calendarSystem:args.calendarSystem,names,name:args.name,summaries:args.summary?{en:args.summary}:undefined,summary:args.summary,countries:['GLOBAL'],sourceIds:[args.sourceId],translationStatus:args.sourceLocale==='en'?'source':'assisted',validationStatus:args.validationStatus,lastVerified:new Date().toISOString().slice(0,10)}}
async function fetchJson(url:string){const response=await fetch(url,{headers:{Accept:'application/json','User-Agent':'SantosDoDia/3.3 (+https://www.santosdodia.com)'},next:{revalidate:21_600},signal:AbortSignal.timeout(TIMEOUT)});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()}
async function fetchText(url:string){const response=await fetch(url,{headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'SantosDoDia/3.3 (+https://www.santosdodia.com)'},next:{revalidate:86_400},signal:AbortSignal.timeout(TIMEOUT)});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.text()}
function dateISO(value:unknown){if(typeof value==='string'){const direct=value.match(/^\d{4}-\d{2}-\d{2}/)?.[0];if(direct)return direct;const parsed=new Date(value);if(!Number.isNaN(parsed.getTime()))return parsed.toISOString().slice(0,10)}if(typeof value==='number'){const parsed=new Date(value<10_000_000_000?value*1000:value);if(!Number.isNaN(parsed.getTime()))return parsed.toISOString().slice(0,10)}}
function litcalEvents(payload:unknown){if(Array.isArray(payload))return payload;const root=record(payload);if(!root)return[];const candidate=root.LitCal??root.litcal??root.events??root.calendar??root.data;if(Array.isArray(candidate))return candidate;const object=record(candidate);return object?Object.values(object).flatMap(value=>Array.isArray(value)?value:[value]):[]}
function parseLitcal(payload:unknown,year:number,locale:Locale,country:string){const out:Observance[]=[];for(const raw of litcalEvents(payload)){const item=record(raw);if(!item)continue;const nested=record(item.date);const date=dateISO(item.date??item.dateISO??item.datetime??nested?.date??item.timestamp),name=text(item.name_lcl??item.name??item.title??item.event_name??record(item.event)?.name);if(!date||!date.startsWith(`${year}-`)||!name)continue;const grade=text(item.grade_lcl??item.grade??item.rank),color=text(item.color);const result=make({sourceId:'litcal-api',externalId:text(item.event_key??item.event_idx??item.id),dateISO:date,name,sourceLocale:locale,tradition:'roman-catholic',calendarSystem:'gregorian',validationStatus:'verified',summary:[grade,color?`Liturgical colour: ${color}`:undefined].filter(Boolean).join(' · ')||undefined});result.countries=[country,'GLOBAL'];out.push(result)}return out}
function decodeHtml(value:string){return value.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&ndash;|&mdash;/gi,'–').replace(/\s+/g,' ').trim()}
const MONTHS=['january','february','march','april','may','june','july','august','september','october','november','december'];
function parseCofe(html:string,year:number){const tokens=[...html.matchAll(/<(h[1-5]|tr|li)[^>]*>([\s\S]*?)<\/\1>/gi)].map(match=>decodeHtml(match[2])).filter(Boolean);const output:Observance[]=[];let month=-1;for(const line of tokens){const lower=line.toLowerCase();const monthIndex=MONTHS.findIndex(value=>lower===value||lower===`${value} ${year}`);if(monthIndex>=0){month=monthIndex;continue}if(month<0)continue;const match=/^(\d{1,2})(?:\s+|[.:–-]+)(.+)$/.exec(line);if(!match)continue;const day=Number(match[1]),name=match[2].replace(/^(principal feast|festival|lesser festival|commemoration)\s*[:–-]?\s*/i,'').trim();if(day<1||day>31||name.length<3||name.length>180||/^(psalm|collect|readings?|weekday|week of|ordinary time)/i.test(name))continue;const date=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;output.push(make({sourceId:'cofe-calendar',dateISO:date,name,sourceLocale:'en',tradition:'anglican',calendarSystem:'gregorian',validationStatus:'verified'}))}return output}
function collectCoptic(value:unknown,output:Array<{id?:string;name:string;summary?:string}>,depth=0){if(depth>6||output.length>80)return;if(Array.isArray(value)){for(const item of value)collectCoptic(item,output,depth+1);return}const item=record(value);if(!item)return;const name=text(item.title??item.name??item.saint??item.commemoration??item.event_name??item.heading);if(name&&name.length<220&&!/^(readings?|metadata|date|day)$/i.test(name)){const id=text(item.id??item.key??item.slug),summary=text(item.summary??item.description??item.story);output.push({id,name,summary})}for(const [key,nested]of Object.entries(item)){if(/^(title|name|saint|commemoration|event_name|heading|summary|description|story|id|key|slug)$/i.test(key))continue;if(typeof nested==='object')collectCoptic(nested,output,depth+1)}}
function matchesRange(item:Observance,range:{month?:number;date?:string}){if(range.date)return item.dateISO===range.date;if(range.month!==undefined)return Number(item.dateISO.slice(5,7))===range.month;return true}

export async function getExpandedChurchObservances(year:number,locale:Locale,filters:ObservanceFilters={},range:{month?:number;date?:string}={}){const checkedAt=new Date().toISOString();const tasks:Array<Promise<{data:Observance[];health:ExpandedSourceHealth}>>=[];
 if((!filters.tradition||filters.tradition==='roman-catholic')&&filters.country){tasks.push((async()=>{const sourceId='litcal-api',country=filters.country!.toUpperCase();try{const localeMap:Partial<Record<Locale,string>>={en:'en_US',es:'es_ES',pt:'pt_PT',fr:'fr_FR',ru:'ru_RU',de:'de_DE',it:'it_IT',pl:'pl_PL'};const payload=await fetchJson(`https://litcal.johnromanodorazio.com/api/v5/calendar/nation/${encodeURIComponent(country)}/${year}?locale=${encodeURIComponent(localeMap[locale]??'en_US')}&year_type=CIVIL`);const data=parseLitcal(payload,year,locale,country).filter(item=>matchesRange(item,range));return{data,health:{sourceId,ok:data.length>0,checkedAt,count:data.length,message:data.length?undefined:'No national Catholic records returned.'}}}catch(error){return{data:[],health:{sourceId,ok:false,checkedAt,count:0,message:error instanceof Error?error.message:'National calendar fetch failed.'}}}})())}
 if(!filters.tradition||filters.tradition==='anglican'){tasks.push((async()=>{const sourceId='cofe-calendar';try{const html=await fetchText('https://www.churchofengland.org/prayer-and-worship/worship-texts-and-resources/common-worship/churchs-year/calendar');const data=parseCofe(html,year).filter(item=>matchesRange(item,range));return{data,health:{sourceId,ok:data.length>0,checkedAt,count:data.length,message:data.length?undefined:'No Anglican records parsed.'}}}catch(error){return{data:[],health:{sourceId,ok:false,checkedAt,count:0,message:error instanceof Error?error.message:'Anglican calendar fetch failed.'}}}})())}
 if((!filters.tradition||filters.tradition==='coptic-orthodox')&&range.date){tasks.push((async()=>{const sourceId='coptic-io';try{const payload=await fetchJson(`https://api.coptic.io/api/synaxarium/${range.date}`);const found:Array<{id?:string;name:string;summary?:string}>=[];collectCoptic(payload,found);const unique=[...new Map(found.map(item=>[item.name.toLowerCase(),item])).values()].slice(0,50);const data=unique.map(item=>make({sourceId,externalId:item.id,dateISO:range.date!,name:item.name,sourceLocale:'en',tradition:'coptic-orthodox',calendarSystem:'coptic',validationStatus:'cross-checked',summary:item.summary}));return{data,health:{sourceId,ok:data.length>0,checkedAt,count:data.length,message:data.length?undefined:'No Coptic commemorations returned.'}}}catch(error){return{data:[],health:{sourceId,ok:false,checkedAt,count:0,message:error instanceof Error?error.message:'Coptic Synaxarium fetch failed.'}}}})())}
 const settled=await Promise.all(tasks);return{data:settled.flatMap(result=>result.data),sourceHealth:settled.map(result=>result.health)}
}
