import type { Locale } from './i18n';

type FeatureCopy={
 navToday:string;navFind:string;navCalendars:string;navLive:string;navCopyright:string;
 findEyebrow:string;findTitle:string;findIntro:string;findPlaceholder:string;findButton:string;
 byProfession:string;byPlace:string;byDate:string;bySaint:string;popular:string;topicResults:string;saintResults:string;
 openTopic:string;openProfile:string;openDay:string;profileIntro:string;associatedWith:string;annualCalendar:string;freeCandle:string;relatedSearches:string;
 liveTitle:string;liveIntro:string;openLive:string;openArchive:string;officialSource:string;liveFallback:string;verifiedOn:string;
 copyrightTitle:string;copyrightIntro:string;copyrightContent:string;copyrightData:string;copyrightImages:string;copyrightEmbeds:string;copyrightCorrections:string;copyrightNoAffiliation:string;
 calendarByTradition:string;calendarByTraditionIntro:string;subscribe:string;
 noMatch:string;dateMatch:string;allResults:string;
};

const en:FeatureCopy={
 navToday:'Today',navFind:'Find a patron saint',navCalendars:'Calendars',navLive:'Live',navCopyright:'Sources, rights and licensing',
 findEyebrow:'Profession · place · date · saint',findTitle:'Find the saint or patron connected with your life.',findIntro:'Search a profession, a place, a day or a saint. Results preserve the Christian tradition and the source behind each association.',findPlaceholder:'Doctors, teachers, Lisbon, 13 June, Saint Anthony…',findButton:'Search',
 byProfession:'By profession',byPlace:'By place',byDate:'By date',bySaint:'By saint',popular:'Popular searches',topicResults:'Patronage and place results',saintResults:'Saints and observances',
 openTopic:'Explore this association',openProfile:'Open saint profile',openDay:'Open feast day',profileIntro:'Profile, patronages, traditions, sources and calendar options.',associatedWith:'Associated patronages and places',annualCalendar:'Add only this saint to my calendar',freeCandle:'Lighting a virtual candle is free and is stored only on this device.',relatedSearches:'Related searches',
 liveTitle:'Christian celebrations and official media',liveIntro:'Verified official live pages and archives from different Christian traditions. When no event is live, the official archive or channel remains available.',openLive:'Open live page',openArchive:'Open official archive',officialSource:'Official source',liveFallback:'Live when scheduled; official recordings remain available.',verifiedOn:'Link checked',
 copyrightTitle:'Sources, rights and licensing',copyrightIntro:'Provenance, copyright and licensing information for data, images, embedded media and editorial content used by Santos do Dia.',copyrightContent:'Original content and software',copyrightData:'Calendar and patronage data',copyrightImages:'Images and visual material',copyrightEmbeds:'Video and live-stream embeds',copyrightCorrections:'Corrections and removal requests',copyrightNoAffiliation:'Institutional names, marks and embedded content remain the property of their respective owners. Their inclusion does not imply sponsorship or institutional endorsement.',
 calendarByTradition:'Calendars by Christian tradition',calendarByTraditionIntro:'Subscribe to a complete tradition or add an individual saint from the saint profile.',subscribe:'Subscribe',
 noMatch:'No matching saint or patronage was found.',dateMatch:'Observances for the selected date',allResults:'All results'
};
const pt:FeatureCopy={
 navToday:'Hoje',navFind:'Encontrar padroeiro',navCalendars:'Calendários',navLive:'Ao vivo',navCopyright:'Fontes, direitos e licenciamento',
 findEyebrow:'Profissão · local · data · santo',findTitle:'Encontre o santo ou padroeiro ligado à sua vida.',findIntro:'Pesquise uma profissão, um local, um dia ou um santo. Os resultados mantêm a tradição cristã e a fonte de cada associação.',findPlaceholder:'Médicos, professores, Lisboa, 13 de junho, Santo António…',findButton:'Pesquisar',
 byProfession:'Por profissão',byPlace:'Por local',byDate:'Por data',bySaint:'Por santo',popular:'Pesquisas populares',topicResults:'Resultados por padroeiro e local',saintResults:'Santos e celebrações',
 openTopic:'Explorar esta associação',openProfile:'Abrir perfil do santo',openDay:'Abrir dia da celebração',profileIntro:'Perfil, padroeiros, tradições, fontes e opções de calendário.',associatedWith:'Padroeiros e locais associados',annualCalendar:'Adicionar apenas este santo ao calendário',freeCandle:'Acender uma vela virtual é gratuito e fica guardado apenas neste dispositivo.',relatedSearches:'Pesquisas relacionadas',
 liveTitle:'Celebrações cristãs e meios oficiais',liveIntro:'Páginas oficiais de transmissão e arquivos verificados de diferentes tradições cristãs. Quando não existe um evento em direto, permanece disponível o canal ou arquivo oficial.',openLive:'Abrir transmissão oficial',openArchive:'Abrir arquivo oficial',officialSource:'Fonte oficial',liveFallback:'Em direto quando agendado; as gravações oficiais permanecem disponíveis.',verifiedOn:'Ligação verificada',
 copyrightTitle:'Fontes, direitos e licenciamento',copyrightIntro:'Informação de proveniência, copyright e licenciamento dos dados, imagens, conteúdos incorporados e textos editoriais utilizados pelo Santos do Dia.',copyrightContent:'Conteúdo original e software',copyrightData:'Dados de calendário e padroeiros',copyrightImages:'Imagens e material visual',copyrightEmbeds:'Vídeos e transmissões incorporadas',copyrightCorrections:'Pedidos de correção e remoção',copyrightNoAffiliation:'Os nomes institucionais, marcas e conteúdos incorporados pertencem aos respetivos titulares. A sua inclusão não implica patrocínio ou aprovação institucional.',
 calendarByTradition:'Calendários por tradição cristã',calendarByTraditionIntro:'Subscreva uma tradição completa ou adicione um santo individual a partir do respetivo perfil.',subscribe:'Subscrever',
 noMatch:'Não foi encontrado um santo ou padroeiro correspondente.',dateMatch:'Celebrações para a data selecionada',allResults:'Todos os resultados'
};
const es:FeatureCopy={
 navToday:'Hoy',navFind:'Encontrar patrono',navCalendars:'Calendarios',navLive:'En directo',navCopyright:'Fuentes, derechos y licencias',
 findEyebrow:'Profesión · lugar · fecha · santo',findTitle:'Encuentre el santo o patrono relacionado con su vida.',findIntro:'Busque una profesión, un lugar, un día o un santo. Los resultados conservan la tradición cristiana y la fuente de cada asociación.',findPlaceholder:'Médicos, profesores, Lisboa, 13 de junio, San Antonio…',findButton:'Buscar',
 byProfession:'Por profesión',byPlace:'Por lugar',byDate:'Por fecha',bySaint:'Por santo',popular:'Búsquedas populares',topicResults:'Resultados de patronazgo y lugar',saintResults:'Santos y celebraciones',
 openTopic:'Explorar esta asociación',openProfile:'Abrir perfil del santo',openDay:'Abrir día de la celebración',profileIntro:'Perfil, patronazgos, tradiciones, fuentes y opciones de calendario.',associatedWith:'Patronazgos y lugares asociados',annualCalendar:'Añadir solo este santo a mi calendario',freeCandle:'Encender una vela virtual es gratuito y se guarda únicamente en este dispositivo.',relatedSearches:'Búsquedas relacionadas',
 liveTitle:'Celebraciones cristianas y medios oficiales',liveIntro:'Páginas oficiales de emisión y archivos verificados de distintas tradiciones cristianas. Cuando no hay un evento en directo, queda disponible el archivo o canal oficial.',openLive:'Abrir emisión oficial',openArchive:'Abrir archivo oficial',officialSource:'Fuente oficial',liveFallback:'En directo cuando está programado; las grabaciones oficiales siguen disponibles.',verifiedOn:'Enlace verificado',
 copyrightTitle:'Fuentes, derechos y licencias',copyrightIntro:'Información de procedencia, copyright y licencias de datos, imágenes, contenidos integrados y textos editoriales utilizados por Santos do Dia.',copyrightContent:'Contenido original y software',copyrightData:'Datos de calendario y patronazgo',copyrightImages:'Imágenes y material visual',copyrightEmbeds:'Vídeos y emisiones integradas',copyrightCorrections:'Solicitudes de corrección y retirada',copyrightNoAffiliation:'Los nombres institucionales, marcas y contenidos integrados pertenecen a sus respectivos titulares. Su inclusión no implica patrocinio o aprobación institucional.',
 calendarByTradition:'Calendarios por tradición cristiana',calendarByTraditionIntro:'Suscríbase a una tradición completa o añada un santo individual desde su perfil.',subscribe:'Suscribirse',
 noMatch:'No se encontró un santo o patronazgo correspondiente.',dateMatch:'Celebraciones para la fecha seleccionada',allResults:'Todos los resultados'
};
const fr:FeatureCopy={
 navToday:"Aujourd’hui",navFind:'Trouver un saint patron',navCalendars:'Calendriers',navLive:'En direct',navCopyright:'Sources, droits et licences',
 findEyebrow:'Profession · lieu · date · saint',findTitle:'Trouvez le saint ou patron lié à votre vie.',findIntro:'Recherchez une profession, un lieu, un jour ou un saint. Les résultats conservent la tradition chrétienne et la source de chaque association.',findPlaceholder:'Médecins, enseignants, Lisbonne, 13 juin, saint Antoine…',findButton:'Rechercher',
 byProfession:'Par profession',byPlace:'Par lieu',byDate:'Par date',bySaint:'Par saint',popular:'Recherches populaires',topicResults:'Résultats de patronage et de lieu',saintResults:'Saints et célébrations',
 openTopic:'Explorer cette association',openProfile:'Ouvrir le profil du saint',openDay:'Ouvrir le jour de fête',profileIntro:'Profil, patronages, traditions, sources et options de calendrier.',associatedWith:'Patronages et lieux associés',annualCalendar:'Ajouter uniquement ce saint à mon calendrier',freeCandle:'Allumer une bougie virtuelle est gratuit et reste enregistré uniquement sur cet appareil.',relatedSearches:'Recherches associées',
 liveTitle:'Célébrations chrétiennes et médias officiels',liveIntro:'Pages officielles de diffusion et archives vérifiées de différentes traditions chrétiennes. Lorsqu’aucun événement n’est en direct, les archives ou la chaîne officielles restent disponibles.',openLive:'Ouvrir la diffusion officielle',openArchive:'Ouvrir les archives officielles',officialSource:'Source officielle',liveFallback:'En direct selon la programmation ; les enregistrements officiels restent disponibles.',verifiedOn:'Lien vérifié',
 copyrightTitle:'Sources, droits et licences',copyrightIntro:'Informations de provenance, de copyright et de licence concernant les données, images, contenus intégrés et textes éditoriaux utilisés par Santos do Dia.',copyrightContent:'Contenu original et logiciel',copyrightData:'Données de calendrier et de patronage',copyrightImages:'Images et matériel visuel',copyrightEmbeds:'Vidéos et directs intégrés',copyrightCorrections:'Demandes de correction et de retrait',copyrightNoAffiliation:'Les noms institutionnels, marques et contenus intégrés restent la propriété de leurs titulaires respectifs. Leur inclusion n’implique aucun parrainage ni approbation institutionnelle.',
 calendarByTradition:'Calendriers par tradition chrétienne',calendarByTraditionIntro:'Abonnez-vous à une tradition complète ou ajoutez un saint individuellement depuis son profil.',subscribe:'S’abonner',
 noMatch:'Aucun saint ou patronage correspondant n’a été trouvé.',dateMatch:'Célébrations pour la date choisie',allResults:'Tous les résultats'
};

export function getFeatureCopy(locale:Locale):FeatureCopy{return locale==='pt'?pt:locale==='es'?es:locale==='fr'?fr:en}
