export const SUPPORTED_LOCALES = ['en', 'pt', 'es', 'fr', 'it', 'el', 'ru'] as const;

export type Locale = (typeof SUPPORTED_LOCALES)[number];
export type LocalizedText = Partial<Record<Locale, string>> & { en: string };

export function normalizeLocale(value: string | null | undefined): Locale {
  const code = String(value ?? '').trim().toLowerCase().split(/[-_]/)[0];
  return (SUPPORTED_LOCALES as readonly string[]).includes(code) ? (code as Locale) : 'en';
}

export function localeFromAcceptLanguage(value: string | null | undefined): Locale {
  if (!value) return 'en';
  for (const token of value.split(',')) {
    const locale = normalizeLocale(token.split(';')[0]);
    if (locale !== 'en' || /^en(?:-|$)/i.test(token.trim())) return locale;
  }
  return 'en';
}

export function localize(text: LocalizedText | undefined, locale: Locale): string {
  if (!text) return '';
  return text[locale] ?? text.en;
}

export const localeLabels: Record<Locale, string> = {
  en: 'English', pt: 'Português', es: 'Español', fr: 'Français', it: 'Italiano', el: 'Ελληνικά', ru: 'Русский'
};

const en = {
  navCalendar:'Calendar', navExplore:'Explore', navSources:'Sources', navDevelopers:'Developers', heroEyebrow:'A global Christian calendar', heroTitle:'Discover the saints and feasts remembered today.', heroBody:'Catholic and Orthodox observances, multilingual discovery, calendar subscriptions and an open API — free for everyone.', today:'Today', viewCalendar:'Open calendar', explore:'Explore observances', catholic:'Catholic', orthodox:'Orthodox', all:'All traditions', saintsToday:'Observances for today', noObservances:'No curated observances are available for this date yet.', openDay:'Open day', addCalendar:'Add to calendar', downloadIcs:'Download ICS', apple:'Apple Calendar', google:'Google Calendar', outlook:'Outlook', calendarTitle:'Christian calendar', calendarIntro:'Browse Catholic and Orthodox observances and build a calendar that fits your interests.', previous:'Previous', next:'Next', tradition:'Tradition', category:'Category', country:'Region', allCategories:'All categories', allRegions:'All regions', saint:'Saint', feast:'Feast', marian:'Marian', apostle:'Apostle', martyr:'Martyr', fast:'Fast', searchTitle:'Explore saints and feasts', searchIntro:'Search by name, patronage, country, category or tradition.', searchPlaceholder:'Search Saint Anthony, doctors, Portugal…', results:'results', noResults:'No matching observances.', sourcesTitle:'Sources and editorial method', sourcesIntro:'The project uses traceable public sources and clearly separates official data, curated summaries and machine-assisted translations.', developersTitle:'Open data for apps and AI', developersIntro:'Use the public REST API, JSON responses and ICS feeds to build calendars, assistants and research tools.', apiDocs:'OpenAPI specification', candle:'Light a candle', candleLit:'Candle lit', candleEmpty:'No candle has been lit on this device today.', candleCount:'on this device', suggestedRegion:'Suggested region', beta:'Curated beta dataset', methodology:'Methodology', global:'Global', footer:'A free, independent Christian calendar project.', disclaimer:'Dates and observances may vary by Church, jurisdiction, rite and calendar system.', dateInvalid:'Invalid date', backCalendar:'Back to calendar', observancesOn:'Observances on', feedAll:'Combined feed', feedCatholic:'Catholic feed', feedOrthodox:'Orthodox feed', sourceOfficial:'Official source', sourceReference:'Reference source', translationStatus:'Translation status', localSuggestion:'Use my region', clear:'Clear'
};

const pt = {
  navCalendar:'Calendário', navExplore:'Explorar', navSources:'Fontes', navDevelopers:'Programadores', heroEyebrow:'Um calendário cristão global', heroTitle:'Descubra os santos e festas recordados hoje.', heroBody:'Celebrações católicas e ortodoxas, pesquisa multilingue, subscrições de calendário e uma API aberta — gratuitamente para todos.', today:'Hoje', viewCalendar:'Abrir calendário', explore:'Explorar celebrações', catholic:'Católica', orthodox:'Ortodoxa', all:'Todas as tradições', saintsToday:'Celebrações de hoje', noObservances:'Ainda não existem celebrações curadas para esta data.', openDay:'Abrir dia', addCalendar:'Adicionar ao calendário', downloadIcs:'Descarregar ICS', apple:'Apple Calendar', google:'Google Calendar', outlook:'Outlook', calendarTitle:'Calendário cristão', calendarIntro:'Consulte celebrações católicas e ortodoxas e construa um calendário adequado aos seus interesses.', previous:'Anterior', next:'Seguinte', tradition:'Tradição', category:'Categoria', country:'Região', allCategories:'Todas as categorias', allRegions:'Todas as regiões', saint:'Santo', feast:'Festa', marian:'Mariana', apostle:'Apóstolo', martyr:'Mártir', fast:'Jejum', searchTitle:'Explorar santos e festas', searchIntro:'Pesquise por nome, padroeiro, país, categoria ou tradição.', searchPlaceholder:'Pesquisar Santo António, médicos, Portugal…', results:'resultados', noResults:'Nenhuma celebração encontrada.', sourcesTitle:'Fontes e método editorial', sourcesIntro:'O projeto utiliza fontes públicas rastreáveis e distingue dados oficiais, resumos editoriais e traduções assistidas por máquina.', developersTitle:'Dados abertos para aplicações e IA', developersIntro:'Use a API REST pública, respostas JSON e feeds ICS para construir calendários, assistentes e ferramentas de investigação.', apiDocs:'Especificação OpenAPI', candle:'Acender uma vela', candleLit:'Vela acesa', candleEmpty:'Ainda não foi acesa uma vela neste dispositivo hoje.', candleCount:'neste dispositivo', suggestedRegion:'Região sugerida', beta:'Base curada em versão beta', methodology:'Metodologia', global:'Global', footer:'Um projeto de calendário cristão gratuito e independente.', disclaimer:'As datas e celebrações podem variar consoante a Igreja, jurisdição, rito e sistema de calendário.', dateInvalid:'Data inválida', backCalendar:'Voltar ao calendário', observancesOn:'Celebrações em', feedAll:'Feed combinado', feedCatholic:'Feed católico', feedOrthodox:'Feed ortodoxo', sourceOfficial:'Fonte oficial', sourceReference:'Fonte de referência', translationStatus:'Estado da tradução', localSuggestion:'Usar a minha região', clear:'Limpar'
};

const es = { ...en, navCalendar:'Calendario', navExplore:'Explorar', navSources:'Fuentes', navDevelopers:'Desarrolladores', heroEyebrow:'Un calendario cristiano global', heroTitle:'Descubre los santos y fiestas recordados hoy.', heroBody:'Celebraciones católicas y ortodoxas, búsqueda multilingüe, suscripciones y una API abierta, gratis para todos.', today:'Hoy', viewCalendar:'Abrir calendario', catholic:'Católica', orthodox:'Ortodoxa', all:'Todas las tradiciones', saintsToday:'Celebraciones de hoy', calendarTitle:'Calendario cristiano', calendarIntro:'Consulta celebraciones católicas y ortodoxas y crea un calendario según tus intereses.', searchTitle:'Explorar santos y fiestas', searchIntro:'Busca por nombre, patronazgo, país, categoría o tradición.', sourcesTitle:'Fuentes y método editorial', developersTitle:'Datos abiertos para aplicaciones e IA', footer:'Un proyecto de calendario cristiano gratuito e independiente.' };
const fr = { ...en, navCalendar:'Calendrier', navExplore:'Explorer', navSources:'Sources', navDevelopers:'Développeurs', heroEyebrow:'Un calendrier chrétien mondial', heroTitle:'Découvrez les saints et fêtes commémorés aujourd’hui.', today:'Aujourd’hui', catholic:'Catholique', orthodox:'Orthodoxe', all:'Toutes les traditions', calendarTitle:'Calendrier chrétien', searchTitle:'Explorer les saints et fêtes', sourcesTitle:'Sources et méthode éditoriale', developersTitle:'Données ouvertes pour applications et IA', footer:'Un projet de calendrier chrétien gratuit et indépendant.' };
const it = { ...en, navCalendar:'Calendario', navExplore:'Esplora', navSources:'Fonti', navDevelopers:'Sviluppatori', heroEyebrow:'Un calendario cristiano globale', heroTitle:'Scopri i santi e le feste ricordati oggi.', today:'Oggi', catholic:'Cattolica', orthodox:'Ortodossa', all:'Tutte le tradizioni', calendarTitle:'Calendario cristiano', searchTitle:'Esplora santi e feste', sourcesTitle:'Fonti e metodo editoriale', developersTitle:'Dati aperti per applicazioni e IA', footer:'Un progetto gratuito e indipendente di calendario cristiano.' };
const el = { ...en, navCalendar:'Ημερολόγιο', navExplore:'Αναζήτηση', navSources:'Πηγές', navDevelopers:'Προγραμματιστές', heroEyebrow:'Ένα παγκόσμιο χριστιανικό ημερολόγιο', heroTitle:'Ανακαλύψτε τους αγίους και τις εορτές της ημέρας.', today:'Σήμερα', catholic:'Καθολική', orthodox:'Ορθόδοξη', all:'Όλες οι παραδόσεις', calendarTitle:'Χριστιανικό ημερολόγιο', searchTitle:'Αναζήτηση αγίων και εορτών', sourcesTitle:'Πηγές και εκδοτική μέθοδος', developersTitle:'Ανοικτά δεδομένα για εφαρμογές και ΤΝ', footer:'Ένα δωρεάν και ανεξάρτητο χριστιανικό ημερολόγιο.' };
const ru = { ...en, navCalendar:'Календарь', navExplore:'Поиск', navSources:'Источники', navDevelopers:'Разработчикам', heroEyebrow:'Глобальный христианский календарь', heroTitle:'Узнайте, каких святых и праздники вспоминают сегодня.', today:'Сегодня', catholic:'Католическая', orthodox:'Православная', all:'Все традиции', calendarTitle:'Христианский календарь', searchTitle:'Поиск святых и праздников', sourcesTitle:'Источники и редакционная методика', developersTitle:'Открытые данные для приложений и ИИ', footer:'Бесплатный независимый христианский календарь.' };

export const ui = { en, pt, es, fr, it, el, ru } as const;
export type UiCopy = (typeof ui)[Locale];
