import type { Locale } from './i18n';

export type LiturgyCopy = {
  nav:string; title:string; intro:string; date:string; calendar:string; language:string; load:string;
  loading:string; sourcePrimary:string; sourceMirror:string; sourceFallback:string; sourceUnavailable:string;
  generalCalendar:string; nationalCalendar:string; diocesanCalendar:string; celebrations:string;
  grade:string; colour:string; season:string; common:string; sundayCycle:string; weekdayCycle:string;
  psalterWeek:string; readings:string; messages:string; provenance:string; noEvents:string;
  lastUpdated:string; rawData:string; sourceCode:string; retry:string;
};

export const liturgyUi: Record<Locale,LiturgyCopy> = {
  en:{nav:'Daily liturgy',title:'Liturgy of any day',intro:'Explore the complete Roman Catholic liturgical information for a selected date and calendar.',date:'Date',calendar:'Calendar',language:'Language',load:'Show liturgy',loading:'Loading liturgical data…',sourcePrimary:'Live LitCal source',sourceMirror:'Local LitCal mirror',sourceFallback:'Curated fallback',sourceUnavailable:'Source temporarily unavailable',generalCalendar:'General Roman Calendar',nationalCalendar:'National calendar',diocesanCalendar:'Diocesan calendar',celebrations:'Celebrations',grade:'Rank',colour:'Liturgical colour',season:'Liturgical season',common:'Common',sundayCycle:'Sunday cycle',weekdayCycle:'Weekday cycle',psalterWeek:'Psalter week',readings:'Readings',messages:'Calculation notes',provenance:'Data provenance',noEvents:'No celebrations were returned for this date.',lastUpdated:'Last updated',rawData:'Structured data',sourceCode:'Open-source engine',retry:'Try again'},
  es:{nav:'Liturgia diaria',title:'Liturgia de cualquier día',intro:'Consulta toda la información litúrgica católica romana para una fecha y un calendario seleccionados.',date:'Fecha',calendar:'Calendario',language:'Idioma',load:'Mostrar liturgia',loading:'Cargando datos litúrgicos…',sourcePrimary:'Fuente LitCal en vivo',sourceMirror:'Espejo local de LitCal',sourceFallback:'Fuente alternativa curada',sourceUnavailable:'Fuente temporalmente no disponible',generalCalendar:'Calendario Romano General',nationalCalendar:'Calendario nacional',diocesanCalendar:'Calendario diocesano',celebrations:'Celebraciones',grade:'Rango',colour:'Color litúrgico',season:'Tiempo litúrgico',common:'Común',sundayCycle:'Ciclo dominical',weekdayCycle:'Ciclo ferial',psalterWeek:'Semana del salterio',readings:'Lecturas',messages:'Notas de cálculo',provenance:'Procedencia de los datos',noEvents:'No se encontraron celebraciones para esta fecha.',lastUpdated:'Última actualización',rawData:'Datos estructurados',sourceCode:'Motor de código abierto',retry:'Volver a intentar'},
  pt:{nav:'Liturgia diária',title:'Liturgia de qualquer dia',intro:'Consulte toda a informação litúrgica católica romana para uma data e um calendário selecionados.',date:'Data',calendar:'Calendário',language:'Idioma',load:'Mostrar liturgia',loading:'A carregar dados litúrgicos…',sourcePrimary:'Fonte LitCal em tempo real',sourceMirror:'Espelho local do LitCal',sourceFallback:'Fonte alternativa curada',sourceUnavailable:'Fonte temporariamente indisponível',generalCalendar:'Calendário Romano Geral',nationalCalendar:'Calendário nacional',diocesanCalendar:'Calendário diocesano',celebrations:'Celebrações',grade:'Grau',colour:'Cor litúrgica',season:'Tempo litúrgico',common:'Comum',sundayCycle:'Ciclo dominical',weekdayCycle:'Ciclo ferial',psalterWeek:'Semana do saltério',readings:'Leituras',messages:'Notas de cálculo',provenance:'Proveniência dos dados',noEvents:'Não foram encontradas celebrações para esta data.',lastUpdated:'Última atualização',rawData:'Dados estruturados',sourceCode:'Motor de código aberto',retry:'Tentar novamente'},
  fr:{nav:'Liturgie du jour',title:'Liturgie de n’importe quel jour',intro:'Consultez toutes les informations liturgiques catholiques romaines pour une date et un calendrier sélectionnés.',date:'Date',calendar:'Calendrier',language:'Langue',load:'Afficher la liturgie',loading:'Chargement des données liturgiques…',sourcePrimary:'Source LitCal en direct',sourceMirror:'Miroir local de LitCal',sourceFallback:'Source alternative validée',sourceUnavailable:'Source temporairement indisponible',generalCalendar:'Calendrier romain général',nationalCalendar:'Calendrier national',diocesanCalendar:'Calendrier diocésain',celebrations:'Célébrations',grade:'Rang',colour:'Couleur liturgique',season:'Temps liturgique',common:'Commun',sundayCycle:'Cycle dominical',weekdayCycle:'Cycle de semaine',psalterWeek:'Semaine du psautier',readings:'Lectures',messages:'Notes de calcul',provenance:'Provenance des données',noEvents:'Aucune célébration trouvée pour cette date.',lastUpdated:'Dernière mise à jour',rawData:'Données structurées',sourceCode:'Moteur open source',retry:'Réessayer'},
  fil:{nav:'Araw-araw na liturhiya',title:'Liturhiya ng anumang araw',intro:'Tingnan ang kumpletong impormasyong liturhikal na Romano Katoliko para sa napiling petsa at kalendaryo.',date:'Petsa',calendar:'Kalendaryo',language:'Wika',load:'Ipakita ang liturhiya',loading:'Naglo-load ng datos liturhikal…',sourcePrimary:'Live na pinagmulan ng LitCal',sourceMirror:'Lokal na salamin ng LitCal',sourceFallback:'Sinuring alternatibong pinagmulan',sourceUnavailable:'Pansamantalang hindi magagamit ang pinagmulan',generalCalendar:'Pangkalahatang Kalendaryong Romano',nationalCalendar:'Pambansang kalendaryo',diocesanCalendar:'Kalendaryong diyosesis',celebrations:'Mga pagdiriwang',grade:'Antas',colour:'Kulay liturhikal',season:'Panahong liturhikal',common:'Karaniwang teksto',sundayCycle:'Siklo ng Linggo',weekdayCycle:'Siklo ng karaniwang araw',psalterWeek:'Linggo ng salteryo',readings:'Mga pagbasa',messages:'Mga tala sa pagkalkula',provenance:'Pinagmulan ng datos',noEvents:'Walang pagdiriwang na natagpuan para sa petsang ito.',lastUpdated:'Huling na-update',rawData:'Nakabalangkas na datos',sourceCode:'Open-source na makina',retry:'Subukan muli'},
  ru:{nav:'Литургия дня',title:'Литургия любого дня',intro:'Полная римско-католическая литургическая информация для выбранной даты и календаря.',date:'Дата',calendar:'Календарь',language:'Язык',load:'Показать литургию',loading:'Загрузка литургических данных…',sourcePrimary:'Источник LitCal в реальном времени',sourceMirror:'Локальное зеркало LitCal',sourceFallback:'Проверенный резервный источник',sourceUnavailable:'Источник временно недоступен',generalCalendar:'Общий римский календарь',nationalCalendar:'Национальный календарь',diocesanCalendar:'Епархиальный календарь',celebrations:'Празднования',grade:'Ранг',colour:'Литургический цвет',season:'Литургическое время',common:'Общее последование',sundayCycle:'Воскресный цикл',weekdayCycle:'Будничный цикл',psalterWeek:'Неделя Псалтири',readings:'Чтения',messages:'Примечания к расчёту',provenance:'Происхождение данных',noEvents:'Для этой даты празднования не найдены.',lastUpdated:'Последнее обновление',rawData:'Структурированные данные',sourceCode:'Открытый движок',retry:'Повторить'},
  sw:{nav:'Liturujia ya kila siku',title:'Liturujia ya siku yoyote',intro:'Tazama taarifa kamili za liturujia ya Kikatoliki ya Roma kwa tarehe na kalenda iliyochaguliwa.',date:'Tarehe',calendar:'Kalenda',language:'Lugha',load:'Onyesha liturujia',loading:'Inapakia data za liturujia…',sourcePrimary:'Chanzo cha LitCal moja kwa moja',sourceMirror:'Nakala ya ndani ya LitCal',sourceFallback:'Chanzo mbadala kilichohakikiwa',sourceUnavailable:'Chanzo hakipatikani kwa muda',generalCalendar:'Kalenda Kuu ya Kirumi',nationalCalendar:'Kalenda ya kitaifa',diocesanCalendar:'Kalenda ya jimbo',celebrations:'Maadhimisho',grade:'Daraja',colour:'Rangi ya liturujia',season:'Majira ya liturujia',common:'Sehemu ya kawaida',sundayCycle:'Mzunguko wa Jumapili',weekdayCycle:'Mzunguko wa siku za juma',psalterWeek:'Wiki ya Zaburi',readings:'Masomo',messages:'Maelezo ya hesabu',provenance:'Asili ya data',noEvents:'Hakuna maadhimisho yaliyopatikana kwa tarehe hii.',lastUpdated:'Ilisasishwa mwisho',rawData:'Data iliyopangwa',sourceCode:'Injini ya chanzo huria',retry:'Jaribu tena'},
  de:{nav:'Tagesliturgie',title:'Liturgie eines beliebigen Tages',intro:'Vollständige römisch-katholische Liturgieinformationen für ein ausgewähltes Datum und einen Kalender.',date:'Datum',calendar:'Kalender',language:'Sprache',load:'Liturgie anzeigen',loading:'Liturgische Daten werden geladen…',sourcePrimary:'Live-LitCal-Quelle',sourceMirror:'Lokaler LitCal-Spiegel',sourceFallback:'Geprüfte Ersatzquelle',sourceUnavailable:'Quelle vorübergehend nicht verfügbar',generalCalendar:'Römischer Generalkalender',nationalCalendar:'Nationalkalender',diocesanCalendar:'Diözesankalender',celebrations:'Feiern',grade:'Rang',colour:'Liturgische Farbe',season:'Liturgische Zeit',common:'Commune',sundayCycle:'Sonntagszyklus',weekdayCycle:'Wochentagszyklus',psalterWeek:'Psalterwoche',readings:'Lesungen',messages:'Berechnungshinweise',provenance:'Datenherkunft',noEvents:'Für dieses Datum wurden keine Feiern gefunden.',lastUpdated:'Zuletzt aktualisiert',rawData:'Strukturierte Daten',sourceCode:'Open-Source-Engine',retry:'Erneut versuchen'},
  it:{nav:'Liturgia del giorno',title:'Liturgia di qualsiasi giorno',intro:'Consulta tutte le informazioni liturgiche cattoliche romane per una data e un calendario selezionati.',date:'Data',calendar:'Calendario',language:'Lingua',load:'Mostra la liturgia',loading:'Caricamento dei dati liturgici…',sourcePrimary:'Fonte LitCal in tempo reale',sourceMirror:'Mirror locale di LitCal',sourceFallback:'Fonte alternativa verificata',sourceUnavailable:'Fonte temporaneamente non disponibile',generalCalendar:'Calendario Romano Generale',nationalCalendar:'Calendario nazionale',diocesanCalendar:'Calendario diocesano',celebrations:'Celebrazioni',grade:'Grado',colour:'Colore liturgico',season:'Tempo liturgico',common:'Comune',sundayCycle:'Ciclo domenicale',weekdayCycle:'Ciclo feriale',psalterWeek:'Settimana del salterio',readings:'Letture',messages:'Note di calcolo',provenance:'Provenienza dei dati',noEvents:'Nessuna celebrazione trovata per questa data.',lastUpdated:'Ultimo aggiornamento',rawData:'Dati strutturati',sourceCode:'Motore open source',retry:'Riprova'},
  pl:{nav:'Liturgia dnia',title:'Liturgia dowolnego dnia',intro:'Pełne rzymskokatolickie informacje liturgiczne dla wybranej daty i kalendarza.',date:'Data',calendar:'Kalendarz',language:'Język',load:'Pokaż liturgię',loading:'Ładowanie danych liturgicznych…',sourcePrimary:'Źródło LitCal na żywo',sourceMirror:'Lokalna kopia LitCal',sourceFallback:'Zweryfikowane źródło zapasowe',sourceUnavailable:'Źródło jest chwilowo niedostępne',generalCalendar:'Ogólny Kalendarz Rzymski',nationalCalendar:'Kalendarz narodowy',diocesanCalendar:'Kalendarz diecezjalny',celebrations:'Obchody',grade:'Ranga',colour:'Kolor liturgiczny',season:'Okres liturgiczny',common:'Teksty wspólne',sundayCycle:'Cykl niedzielny',weekdayCycle:'Cykl dni powszednich',psalterWeek:'Tydzień psałterza',readings:'Czytania',messages:'Uwagi obliczeniowe',provenance:'Pochodzenie danych',noEvents:'Nie znaleziono obchodów dla tej daty.',lastUpdated:'Ostatnia aktualizacja',rawData:'Dane strukturalne',sourceCode:'Silnik open source',retry:'Spróbuj ponownie'}
};

export function liturgyLabel(locale:Locale){return liturgyUi[locale].nav}
