import { localize,type Locale,type LocalizedText } from './i18n';
import type { Tradition } from '../data/observances';

export type HolidayKind='fixed'|'movable';
export type ReligiousHoliday={id:string;date:string;name:string;kind:HolidayKind;publicHoliday:boolean;tradition?:Tradition;localName?:string;source:string};
export type NagerHoliday={date:string;localName:string;name:string;countryCode:string;fixed:boolean;global:boolean;counties?:string[]|null;types?:string[]};

const LABELS:Record<string,LocalizedText>={
 christmas:{en:'Christmas Day',pt:'Natal',es:'Navidad',fr:'Noël',de:'Weihnachten',it:'Natale',pl:'Boże Narodzenie',ru:'Рождество Христово',fil:'Pasko',sw:'Krismasi'},
 christmasEve:{en:'Christmas Eve',pt:'Véspera de Natal',es:'Nochebuena',fr:'Veille de Noël',de:'Heiligabend',it:'Vigilia di Natale',pl:'Wigilia',ru:'Сочельник',fil:'Bisperas ng Pasko',sw:'Mkesha wa Krismasi'},
 stephen:{en:'Saint Stephen’s Day',pt:'Dia de Santo Estêvão',es:'Día de San Esteban',fr:'Saint-Étienne',de:'Stephanstag',it:'Santo Stefano',pl:'Świętego Szczepana',ru:'День святого Стефана',fil:'Araw ni San Esteban',sw:'Siku ya Mtakatifu Stefano'},
 epiphany:{en:'Epiphany',pt:'Epifania',es:'Epifanía',fr:'Épiphanie',de:'Heilige Drei Könige',it:'Epifania',pl:'Objawienie Pańskie',ru:'Богоявление',fil:'Epipanya',sw:'Epifania'},
 annunciation:{en:'Annunciation',pt:'Anunciação do Senhor',es:'Anunciación',fr:'Annonciation',de:'Verkündigung des Herrn',it:'Annunciazione',pl:'Zwiastowanie Pańskie',ru:'Благовещение',fil:'Pagpapahayag',sw:'Bikira Kupashwa Habari'},
 joseph:{en:'Saint Joseph’s Day',pt:'Dia de São José',es:'Día de San José',fr:'Saint-Joseph',de:'Josefstag',it:'San Giuseppe',pl:'Świętego Józefa',ru:'День святого Иосифа',fil:'Araw ni San Jose',sw:'Siku ya Mtakatifu Yosefu'},
 goodFriday:{en:'Good Friday',pt:'Sexta-feira Santa',es:'Viernes Santo',fr:'Vendredi saint',de:'Karfreitag',it:'Venerdì Santo',pl:'Wielki Piątek',ru:'Великая пятница',fil:'Biyernes Santo',sw:'Ijumaa Kuu'},
 holySaturday:{en:'Holy Saturday',pt:'Sábado Santo',es:'Sábado Santo',fr:'Samedi saint',de:'Karsamstag',it:'Sabato Santo',pl:'Wielka Sobota',ru:'Великая суббота',fil:'Sabado de Gloria',sw:'Jumamosi Kuu'},
 easter:{en:'Easter Sunday',pt:'Domingo de Páscoa',es:'Domingo de Pascua',fr:'Dimanche de Pâques',de:'Ostersonntag',it:'Domenica di Pasqua',pl:'Niedziela Wielkanocna',ru:'Пасха',fil:'Linggo ng Pagkabuhay',sw:'Jumapili ya Pasaka'},
 easterMonday:{en:'Easter Monday',pt:'Segunda-feira de Páscoa',es:'Lunes de Pascua',fr:'Lundi de Pâques',de:'Ostermontag',it:'Lunedì dell’Angelo',pl:'Poniedziałek Wielkanocny',ru:'Пасхальный понедельник',fil:'Lunes ng Pasko ng Pagkabuhay',sw:'Jumatatu ya Pasaka'},
 ashWednesday:{en:'Ash Wednesday',pt:'Quarta-feira de Cinzas',es:'Miércoles de Ceniza',fr:'Mercredi des Cendres',de:'Aschermittwoch',it:'Mercoledì delle Ceneri',pl:'Środa Popielcowa',ru:'Пепельная среда',fil:'Miyerkules ng Abo',sw:'Jumatano ya Majivu'},
 palmSunday:{en:'Palm Sunday',pt:'Domingo de Ramos',es:'Domingo de Ramos',fr:'Dimanche des Rameaux',de:'Palmsonntag',it:'Domenica delle Palme',pl:'Niedziela Palmowa',ru:'Вербное воскресенье',fil:'Linggo ng Palaspas',sw:'Jumapili ya Matawi'},
 maundyThursday:{en:'Maundy Thursday',pt:'Quinta-feira Santa',es:'Jueves Santo',fr:'Jeudi saint',de:'Gründonnerstag',it:'Giovedì Santo',pl:'Wielki Czwartek',ru:'Великий четверг',fil:'Huwebes Santo',sw:'Alhamisi Kuu'},
 ascension:{en:'Ascension of the Lord',pt:'Ascensão do Senhor',es:'Ascensión del Señor',fr:'Ascension',de:'Christi Himmelfahrt',it:'Ascensione',pl:'Wniebowstąpienie Pańskie',ru:'Вознесение Господне',fil:'Pag-akyat sa Langit',sw:'Kupaa kwa Bwana'},
 pentecost:{en:'Pentecost',pt:'Pentecostes',es:'Pentecostés',fr:'Pentecôte',de:'Pfingsten',it:'Pentecoste',pl:'Zesłanie Ducha Świętego',ru:'Пятидесятница',fil:'Pentekostes',sw:'Pentekoste'},
 corpusChristi:{en:'Corpus Christi',pt:'Corpo de Deus',es:'Corpus Christi',fr:'Fête-Dieu',de:'Fronleichnam',it:'Corpus Domini',pl:'Boże Ciało',ru:'Праздник Тела и Крови Христовых',fil:'Corpus Christi',sw:'Mwili na Damu ya Kristo'},
 peterPaul:{en:'Saints Peter and Paul',pt:'São Pedro e São Paulo',es:'San Pedro y San Pablo',fr:'Saints Pierre et Paul',de:'Peter und Paul',it:'Santi Pietro e Paolo',pl:'Świętych Piotra i Pawła',ru:'Святые Пётр и Павел',fil:'Sina San Pedro at San Pablo',sw:'Watakatifu Petro na Paulo'},
 assumption:{en:'Assumption of Mary',pt:'Assunção de Nossa Senhora',es:'Asunción de María',fr:'Assomption',de:'Mariä Himmelfahrt',it:'Assunzione di Maria',pl:'Wniebowzięcie Najświętszej Maryi Panny',ru:'Успение Богородицы',fil:'Pag-akyat ni Maria',sw:'Kupalizwa kwa Maria'},
 cross:{en:'Exaltation of the Holy Cross',pt:'Exaltação da Santa Cruz',es:'Exaltación de la Santa Cruz',fr:'Exaltation de la Sainte-Croix',de:'Kreuzerhöhung',it:'Esaltazione della Santa Croce',pl:'Podwyższenie Krzyża Świętego',ru:'Воздвижение Креста Господня',fil:'Pagdakila sa Banal na Krus',sw:'Kuinuliwa kwa Msalaba Mtakatifu'},
 allSaints:{en:'All Saints’ Day',pt:'Dia de Todos os Santos',es:'Día de Todos los Santos',fr:'Toussaint',de:'Allerheiligen',it:'Tutti i Santi',pl:'Wszystkich Świętych',ru:'День всех святых',fil:'Araw ng mga Santo',sw:'Siku ya Watakatifu Wote'},
 allSouls:{en:'All Souls’ Day',pt:'Comemoração dos Fiéis Defuntos',es:'Día de los Fieles Difuntos',fr:'Commémoration des fidèles défunts',de:'Allerseelen',it:'Commemorazione dei defunti',pl:'Dzień Zaduszny',ru:'День поминовения усопших',fil:'Araw ng mga Kaluluwa',sw:'Siku ya Marehemu'},
 immaculate:{en:'Immaculate Conception',pt:'Imaculada Conceição',es:'Inmaculada Concepción',fr:'Immaculée Conception',de:'Mariä Empfängnis',it:'Immacolata Concezione',pl:'Niepokalane Poczęcie',ru:'Непорочное зачатие',fil:'Kalinis-linisang Paglilihi',sw:'Mkingiwa Dhambi ya Asili'},
 reformation:{en:'Reformation Day',pt:'Dia da Reforma',es:'Día de la Reforma',fr:'Fête de la Réformation',de:'Reformationstag',it:'Festa della Riforma',pl:'Święto Reformacji',ru:'День Реформации',fil:'Araw ng Repormasyon',sw:'Siku ya Matengenezo'}
};
function addDays(date:Date,days:number){const next=new Date(date);next.setUTCDate(next.getUTCDate()+days);return next}
function iso(date:Date){return date.toISOString().slice(0,10)}
export function gregorianEaster(year:number){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=(h+l-7*m+114)%31+1;return new Date(Date.UTC(year,month-1,day))}
export function orthodoxEaster(year:number){const a=year%4,b=year%7,c=year%19,d=(19*c+15)%30,e=(2*a+4*b-d+34)%7,month=Math.floor((d+e+114)/31),day=(d+e+114)%31+1,julian=new Date(Date.UTC(year,month-1,day)),shift=Math.floor(year/100)-Math.floor(year/400)-2;return addDays(julian,shift)}
function fixed(year:number,month:number,day:number){return new Date(Date.UTC(year,month-1,day))}
function label(key:string,locale:Locale){return localize(LABELS[key]??{en:key},locale)}
function entry(key:string,date:Date,locale:Locale,kind:HolidayKind,tradition:Tradition):ReligiousHoliday{return{id:`${tradition}-${key}-${iso(date)}`,date:iso(date),name:label(key,locale),kind,publicHoliday:false,tradition,source:'calculated-liturgical-calendar'}}
function westernDates(year:number,locale:Locale,tradition:Tradition){const easter=gregorianEaster(year);return[
 entry('epiphany',fixed(year,1,6),locale,'fixed',tradition),entry('joseph',fixed(year,3,19),locale,'fixed',tradition),entry('annunciation',fixed(year,3,25),locale,'fixed',tradition),entry('ashWednesday',addDays(easter,-46),locale,'movable',tradition),entry('palmSunday',addDays(easter,-7),locale,'movable',tradition),entry('maundyThursday',addDays(easter,-3),locale,'movable',tradition),entry('goodFriday',addDays(easter,-2),locale,'movable',tradition),entry('holySaturday',addDays(easter,-1),locale,'movable',tradition),entry('easter',easter,locale,'movable',tradition),entry('easterMonday',addDays(easter,1),locale,'movable',tradition),entry('ascension',addDays(easter,39),locale,'movable',tradition),entry('pentecost',addDays(easter,49),locale,'movable',tradition),entry('corpusChristi',addDays(easter,60),locale,'movable',tradition),entry('peterPaul',fixed(year,6,29),locale,'fixed',tradition),entry('assumption',fixed(year,8,15),locale,'fixed',tradition),entry('cross',fixed(year,9,14),locale,'fixed',tradition),entry('allSaints',fixed(year,11,1),locale,'fixed',tradition),entry('allSouls',fixed(year,11,2),locale,'fixed',tradition),entry('immaculate',fixed(year,12,8),locale,'fixed',tradition),entry('christmas',fixed(year,12,25),locale,'fixed',tradition)
 ]}
function easternDates(year:number,locale:Locale,tradition:Tradition){const easter=orthodoxEaster(year);return[entry('epiphany',fixed(year,1,19),locale,'fixed',tradition),entry('annunciation',fixed(year,4,7),locale,'fixed',tradition),entry('palmSunday',addDays(easter,-7),locale,'movable',tradition),entry('goodFriday',addDays(easter,-2),locale,'movable',tradition),entry('holySaturday',addDays(easter,-1),locale,'movable',tradition),entry('easter',easter,locale,'movable',tradition),entry('ascension',addDays(easter,39),locale,'movable',tradition),entry('pentecost',addDays(easter,49),locale,'movable',tradition),entry('peterPaul',fixed(year,7,12),locale,'fixed',tradition),entry('assumption',fixed(year,8,28),locale,'fixed',tradition),entry('cross',fixed(year,9,27),locale,'fixed',tradition),entry('christmas',fixed(year,1,7),locale,'fixed',tradition)]}
export function calculatedChurchDates(year:number,locale:Locale,tradition:'all'|Tradition){const traditions:Tradition[]=tradition==='all'?['roman-catholic','anglican','greek-orthodox','eastern-orthodox','coptic-orthodox','armenian-apostolic','ethiopian-orthodox','syriac-orthodox']:[tradition];return traditions.flatMap(value=>['greek-orthodox','eastern-orthodox','coptic-orthodox','ethiopian-orthodox','syriac-orthodox'].includes(value)?easternDates(year,locale,value):westernDates(year,locale,value)).sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name))}
export function inferChristianHoliday(name:string){const n=name.toLowerCase();if(/christmas eve|nochebuena|heiligabend/.test(n))return'christmasEve';if(/christmas|nativity/.test(n))return'christmas';if(/st\.? stephen|saint stephen|boxing day/.test(n))return'stephen';if(/epiphany|three kings|theophany/.test(n))return'epiphany';if(/good friday/.test(n))return'goodFriday';if(/holy saturday/.test(n))return'holySaturday';if(/easter monday/.test(n))return'easterMonday';if(/easter|pascha/.test(n))return'easter';if(/ascension/.test(n))return'ascension';if(/pentecost|whit sunday/.test(n))return'pentecost';if(/whit monday/.test(n))return'pentecost';if(/corpus christi/.test(n))return'corpusChristi';if(/assumption/.test(n))return'assumption';if(/all saints/.test(n))return'allSaints';if(/all souls/.test(n))return'allSouls';if(/immaculate conception/.test(n))return'immaculate';if(/reformation/.test(n))return'reformation';if(/annunciation/.test(n))return'annunciation';if(/saint joseph|st\.? joseph/.test(n))return'joseph';if(/peter.*paul|paul.*peter/.test(n))return'peterPaul';return undefined}
export function localizePublicHoliday(item:NagerHoliday,locale:Locale):ReligiousHoliday|undefined{const key=inferChristianHoliday(`${item.name} ${item.localName}`);if(!key)return;return{id:`public-${item.countryCode}-${item.date}-${key}`,date:item.date,name:label(key,locale),kind:item.fixed?'fixed':'movable',publicHoliday:true,localName:item.localName,source:'nager-date-public-holidays'}}
