export type RomanSourceTier='primary'|'exact-mirror'|'calculation-backup'|'official-validation';
export type RomanSource={id:string;name:string;tier:RomanSourceTier;url:string;license?:string;coverage:string;usage:string;copyPolicy:'mirror'|'code-mirror'|'query'|'link-only'};

export const ROMAN_SOURCE_STACK:RomanSource[]=[
 {id:'litcal-live',name:'Liturgical Calendar API',tier:'primary',url:'https://litcal.johnromanodorazio.com/',license:'Apache-2.0',coverage:'General Roman Calendar, national and diocesan calendars, 1970–9999, multiple locales, precedence rules, decrees and calculation messages.',usage:'Primary live calculation and structured source.',copyPolicy:'query'},
 {id:'litcal-response-mirror',name:'Santos do Dia LitCal response mirror',tier:'exact-mirror',url:'/api/v1/liturgy',coverage:'Exact raw upstream responses for operational years, site locales, and published national and diocesan calendars.',usage:'Automatic runtime fallback when the primary API is unavailable.',copyPolicy:'mirror'},
 {id:'litcal-source-mirror',name:'Santos do Dia LitCal source mirror',tier:'exact-mirror',url:'https://github.com/Liturgical-Calendar/LiturgicalCalendarAPI',license:'Apache-2.0',coverage:'Stable upstream calculation engine, source data, schemas, translations and tests.',usage:'Regenerate historical or missing responses independently of the hosted service.',copyPolicy:'code-mirror'},
 {id:'parish-companion',name:'Parish Companion Ordo',tier:'calculation-backup',url:'https://parishcompanion.org/',license:'MIT',coverage:'Roman calendar, seasons, rank, colour, transfer rules and cycles; national coverage begins with Australia.',usage:'Independent automated comparison where the requested country is supported.',copyPolicy:'query'},
 {id:'romcal',name:'romcal',tier:'calculation-backup',url:'https://github.com/romcal/romcal',license:'MIT',coverage:'Independent General Roman Calendar calculation, national calendars, seasons, cycles, colours and localization.',usage:'Secondary calculation engine and regression comparison.',copyPolicy:'code-mirror'},
 {id:'usccb-calendar',name:'USCCB annual liturgical calendars',tier:'official-validation',url:'https://www.usccb.org/prayer-worship/liturgical-year',coverage:'Official United States celebration, rank, colour, Lectionary references and Psalter cycle.',usage:'Human and automated metadata validation for the United States; source documents are linked, not reproduced.',copyPolicy:'link-only'},
 {id:'holy-see-decrees',name:'Dicastery for Divine Worship and the Discipline of the Sacraments',tier:'official-validation',url:'https://www.vatican.va/content/romancuria/en/dicasteri/dicastero-culto-divino-e-disciplina-sacramenti/documenti.html',coverage:'Authoritative decrees and changes to the General Roman Calendar.',usage:'Final authority for additions and calendar changes.',copyPolicy:'link-only'}
];
